# Generated by Django 5.2.4 on 2025-08-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
